# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dff8df4c00826a879b3ea9d77d67f37e59a3570f2a33dff6622182abbcbf28fb56b3aeeedab7475ab085bf8b3eb922f32ee7eb66f997892b6e39100d20fea1ff

test:
  secret_key_base: 1c23582f17bdf26a01f1925f79c4063d198f67d114e26376bddb003a1e687841f541d27c23f2918fddfe564798f33b1b22c657460294d57b7f45ec1055c841e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
